### ISSUE TITLE
ImportError: cannot import name Connection

### ISSUE THREAD

**Issue by clovis818** [joshmarshall/mogo#20]
File "/Users/Sam/Envs/AdiosScraper/lib/python2.7/site-packages/mogo/connection.py", line 3, in <module>
    from pymongo import Connection as PyConnection
ImportError: cannot import name Connection

**Comment by clovis818** [comment]
Works with PyMongo==2.7 but fails with PyMongo==3.0

**Comment by wordsforthewise** [comment]
I'm getting the same error with python 2.7 on windows 7, pymongo 3.0.3
